<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\KurvaTableSetting;

class KurvaTableSettingSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $settings = [
            [
                'nama_tabel' => 'table1',
                'nama' => 'Tabel 1',
                'judul' => 'Grafik Berat Badan Menurut Umur 0 - 60 Bulan',
                'ket_y' => 'Berat (Kg)',
                'y_min' => 0,
                'y_max' => 31,
                'y_mayor' => 2,
                'y_minor' => 1,
                'y_unit' => 'Kg',
                'ket_x' => 'Umur (Tahun Bulan)',
                'x_min' => 0,
                'x_max' => 60,
                'x_mayor' => 2,
                'x_minor' => 1,
                'x_unit' => 'Bulan',
                'sumbu_y' => 'Berat',
                'sumbu_x' => 'Usia Hari',
            ],
            [
                'nama_tabel' => 'table2',
                'nama' => 'Tabel 2',
                'judul' => 'Grafik Panjang / Tinggi Badan Menurut Umur 0 - 60 Bulan',
                'ket_y' => 'Panjang / Tinggi (Cm)',
                'y_min' => 40,
                'y_max' => 125,
                'y_mayor' => 5,
                'y_minor' => 1,
                'y_unit' => 'Cm',
                'ket_x' => 'Umur (Tahun Bulan)',
                'x_min' => 0,
                'x_max' => 60,
                'x_mayor' => 2,
                'x_minor' => 1,
                'x_unit' => 'Bulan',
                'sumbu_y' => 'Panjang',
                'sumbu_x' => 'Usia Hari',
            ],
            [
                'nama_tabel' => 'table3',
                'nama' => 'Tabel 3',
                'judul' => 'Grafik Lingkaran Kepala Menurut Umur 0 - 60 Bulan',
                'ket_y' => 'Lingkaran Kepala (Cm)',
                'y_min' => 30,
                'y_max' => 56,
                'y_mayor' => 2,
                'y_minor' => 0.5,
                'y_unit' => 'Cm',
                'ket_x' => 'Umur (Tahun Bulan)',
                'x_min' => 0,
                'x_max' => 60,
                'x_mayor' => 2,
                'x_minor' => 1,
                'x_unit' => 'Bulan',
                'sumbu_y' => 'Lingkar Kepala',
                'sumbu_x' => 'Usia Hari',
            ],
            [
                'nama_tabel' => 'table4',
                'nama' => 'Tabel 4',
                'judul' => 'Grafik Berat Badan Menurut Panjang / Tinggi 0 - 60 Bulan',
                'ket_y' => 'Berat (Kg)',
                'y_min' => 0,
                'y_max' => 34,
                'y_mayor' => 2,
                'y_minor' => 1,
                'y_unit' => 'Kg',
                'ket_x' => 'Panjang / Tinggi (Cm)',
                'x_min' => 45,
                'x_max' => 120,
                'x_mayor' => 5,
                'x_minor' => 1,
                'x_unit' => 'Cm',
                'sumbu_y' => 'Berat',
                'sumbu_x' => 'Panjang',
            ],
            [
                'nama_tabel' => 'table5',
                'nama' => 'Tabel 5',
                'judul' => 'Grafik Indeks Massa Tubuh Menurut Umur 0 - 60 Bulan',
                'ket_y' => 'IMT (Kg/m²)',
                'y_min' => 9,
                'y_max' => 23,
                'y_mayor' => 1,
                'y_minor' => 0.2,
                'y_unit' => 'Kg/m²',
                'ket_x' => 'Umur (Tahun Bulan)',
                'x_min' => 0,
                'x_max' => 60,
                'x_mayor' => 2,
                'x_minor' => 1,
                'x_unit' => 'Bulan',
                'sumbu_y' => 'IMT',
                'sumbu_x' => 'Usia Hari',
            ],
            [
                'nama_tabel' => 'table6',
                'nama' => 'Tabel 6',
                'judul' => 'Grafik Berat Badan Menurut Umur 5 - 10 Tahun',
                'ket_y' => 'Berat (Kg)',
                'y_min' => 10,
                'y_max' => 60,
                'y_mayor' => 5,
                'y_minor' => 1,
                'y_unit' => 'Kg',
                'ket_x' => 'Umur (Tahun Bulan)',
                'x_min' => 5,
                'x_max' => 10,
                'x_mayor' => 3, // Asumsi 3 bl = 3 bulan
                'x_minor' => 1,  // Asumsi 1 bl = 1 bulan
                'x_unit' => 'Tahun',
                'sumbu_y' => 'Berat',
                'sumbu_x' => 'Usia Hari',
            ],
            [
                'nama_tabel' => 'table7',
                'nama' => 'Tabel 7',
                'judul' => 'Grafik Indeks Massa Tubuh Menurut Umur 5 - 19 Tahun',
                'ket_y' => 'IMT (Kg/m²)',
                'y_min' => 11,
                'y_max' => 37,
                'y_mayor' => 2,
                'y_minor' => 0.5,
                'y_unit' => 'Kg/m²',
                'ket_x' => 'Umur (Tahun Bulan)',
                'x_min' => 5,
                'x_max' => 19,
                'x_mayor' => 3, // Asumsi 3 bl = 3 bulan
                'x_minor' => 1,  // Asumsi 1 bl = 1 bulan
                'x_unit' => 'Tahun',
                'sumbu_y' => 'IMT',
                'sumbu_x' => 'Usia Bulan',
            ],
            [
                'nama_tabel' => 'table8',
                'nama' => 'Tabel 8',
                'judul' => 'Grafik Tinggi Badan Menurut Umur 5 - 19 Tahun',
                'ket_y' => 'Tinggi (Cm)',
                'y_min' => 90,
                'y_max' => 200,
                'y_mayor' => 10,
                'y_minor' => 5,
                'y_unit' => 'Cm',
                'ket_x' => 'Umur (Tahun Bulan)',
                'x_min' => 0,
                'x_max' => 60,
                'x_mayor' => 3,
                'x_minor' => 1,
                'x_unit' => 'Bulan',
                'sumbu_y' => 'Tinggi',
                'sumbu_x' => 'Usia Bulan',
            ],
            [
                'nama_tabel' => 'table9',
                'nama' => 'Tabel 9',
                'judul' => 'Grafik Berat Badan Menurut Umur 27 – 64 Minggu Usia Gestasi',
                'ket_y' => 'Berat Badan (Kg)',
                'y_min' => 0,
                'y_max' => 12,
                'y_mayor' => 0.5,
                'y_minor' => 0.1,
                'y_unit' => 'Kg',
                'ket_x' => 'Usia Gestasi (Minggu)',
                'x_min' => 27,
                'x_max' => 64,
                'x_mayor' => 1,
                'x_minor' => 0.167,
                'x_unit' => 'Minggu',
                'sumbu_y' => 'Berat Badan',
                'sumbu_x' => 'Usia Gestasi',
            ],
            [
                'nama_tabel' => 'table10',
                'nama' => 'Tabel 10',
                'judul' => 'Grafik Tinggi Badan Menurut Umur 27 – 64 Minggu Usia Gestasi',
                'ket_y' => 'Tinggi Badan (Cm)',
                'y_min' => 26,
                'y_max' => 76,
                'y_mayor' => 2,
                'y_minor' => 0.5,
                'y_unit' => 'Cm',
                'ket_x' => 'Usia Gestasi (Minggu)',
                'x_min' => 27,
                'x_max' => 64,
                'x_mayor' => 1,
                'x_minor' => 0.167,
                'x_unit' => 'Minggu',
                'sumbu_y' => 'Berat Badan',
                'sumbu_x' => 'Usia Gestasi',
            ],
            [
                'nama_tabel' => 'table11',
                'nama' => 'Tabel 11',
                'judul' => 'Grafik Lingkar Kepala Menurut Umur 27 – 64 Minggu Usia Gestasi',
                'ket_y' => 'Lingkar Kepala (Cm)',
                'y_min' => 19,
                'y_max' => 48,
                'y_mayor' => 1,
                'y_minor' => 0.2,
                'y_unit' => 'Cm',
                'ket_x' => 'Usia Gestasi (Minggu)',
                'x_min' => 27,
                'x_max' => 64,
                'x_mayor' => 1,
                'x_minor' => 0.167,
                'x_unit' => 'Minggu',
                'sumbu_y' => 'Berat Badan',
                'sumbu_x' => 'Usia Gestasi',
            ],
            [
                'nama_tabel' => 'table12',
                'nama' => 'Tabel 12',
                'judul' => 'Grafik Berat Badan Menurut Panjang Badan 27 – 64 Minggu Usia Gestasi',
                'ket_y' => 'Berat Badan (Kg)',
                'y_min' => 0,
                'y_max' => 14,
                'y_mayor' => 1,
                'y_minor' => 0.1,
                'y_unit' => 'Kg',
                'ket_x' => 'Panjang Badan (Cm)',
                'x_min' => 36,
                'x_max' => 76,
                'x_mayor' => 1,
                'x_minor' => 0.1,
                'x_unit' => 'Cm',
                'sumbu_y' => 'Berat Badan',
                'sumbu_x' => 'Panjang Badan',
            ],
        ];

        foreach ($settings as $setting) {
            KurvaTableSetting::create($setting);
        }
    }
}
