services:
    app:
        container_name: sikurva
        build: .
        image: sikurva-app
        env_file: .env
        ports:
            - "8007:8000"
        volumes:
            - ./storage:/var/www/html/storage
        networks:
            - together-network
        restart: unless-stopped

    queue:
        container_name: sikurva-queue
        build: .
        image: sikurva-app
        env_file: .env
        command:
            [
                "sh",
                "-c",
                "php artisan queue:work --sleep=3 --tries=3 --max-time=3600",
            ]
        volumes:
            - ./storage:/var/www/html/storage
        networks:
            - together-network
        depends_on:
            - app
        restart: unless-stopped

    scheduler:
        container_name: sikurva-scheduler
        build: .
        image: sikurva-app
        env_file: .env
        command:
            [
                "sh",
                "-c",
                "echo '* * * * * cd /var/www/html && php artisan schedule:run >> /dev/null 2>&1' > /etc/crontabs/root && crond -f -l 2",
            ]
        volumes:
            - ./storage:/var/www/html/storage
        networks:
            - together-network
        depends_on:
            - app
        restart: unless-stopped

networks:
    together-network:
        external: true
